import { ClerkLoaded, ClerkLoading, SignedIn, SignedOut } from "@clerk/nextjs";
import { SignUpButton } from "@clerk/nextjs";
import { Button, Link } from "@nextui-org/react";
import { BookMarked, CloudUpload, WandSparkles } from "lucide-react";

const features = [
  {
    icon: <WandSparkles />,
    title: "AI-Generated Flashcards",
    description:
      "Instantly create flashcards from your text using advanced AI technology.",
  },
  {
    icon: <BookMarked />,
    title: "Save and Revisit",
    description:
      "Easily save your flashcards and access them anytime for quick review.",
  },
  {
    icon: <CloudUpload />,
    title: "Cloud Sync",
    description: "Access your flashcards from any device, anytime, anywhere.",
  },
];

export default function Home() {
  return (
    <main>
      <section id="home" className="bg-white dark:bg-gray-900">
        <div className="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16 lg:px-12">
          <h1 className="mb-4 text-4xl font-extrabold xl:mx-48 tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">
            Transform Your Learning with AI-Powered Flashcards
          </h1>
          <p className="mb-8 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400">
            Elevate your study sessions with smart, personalized flashcards
            generated by cutting-edge AI. Study smarter, not harder.
          </p>
          <div className="flex flex-col mb-8 lg:mb-16 space-y-4 sm:flex-row sm:justify-center sm:space-y-0 sm:space-x-4">
            <ClerkLoading>
              <Button
                color="primary"
                className="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center rounded-lg"
                isLoading
              >
                Get Started
              </Button>
              <Button
                variant="ghost"
                className="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center rounded-lg"
                isLoading
              >
                Learn More
              </Button>
            </ClerkLoading>
            <ClerkLoaded>
              <SignedIn>
                <Button
                  color="primary"
                  className="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center rounded-lg"
                  as={Link}
                  href="/generate"
                >
                  Generate Flashcards
                </Button>
              </SignedIn>
              <SignedOut>
                <SignUpButton mode="modal">
                  <Button
                    color="primary"
                    className="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center rounded-lg"
                  >
                    Get Started
                  </Button>
                </SignUpButton>
              </SignedOut>
              <Button
                variant="ghost"
                className="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center rounded-lg"
                as={Link}
                href="#features"
              >
                Learn More
              </Button>
            </ClerkLoaded>
          </div>
        </div>
      </section>
      <section id="features" className="bg-white dark:bg-gray-900">
        <div className="py-8 px-4 mx-auto flex flex-col justify-center items-center w-full text-center lg:py-16 lg:px-12">
          <div className="max-w-screen-md mb-8 lg:mb-16">
            <h2 className="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">
              Key Features of AI Flashcards App
            </h2>
            <p className="text-gray-500 sm:text-xl dark:text-gray-400">
              Our app is designed to enhance your learning experience through
              innovative features that make studying more efficient and
              enjoyable.
            </p>
          </div>
          <div className="space-y-8 md:grid md:grid-cols-2 lg:grid-cols-3 md:gap-12 md:space-y-0">
            {features.map((feature, index) => (
              <div
                key={index}
                className="flex flex-col justify-center items-center "
              >
                <div className="flex justify-center items-center mb-4 w-10 h-10 rounded-full lg:h-12 lg:w-12 bg-primary-100 dark:bg-primary-900 text-primary-600 dark:text-primary-300">
                  {feature.icon}
                </div>
                <h3 className="mb-2 text-xl font-bold dark:text-white">
                  {feature.title}
                </h3>
                <p className="text-gray-500 dark:text-gray-400">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* <Box sx={{ my: 6, padding: "3rem" }}>
        <Typography variant="h4" component="h2" gutterBottom>
          Features
        </Typography>
        <Grid2 container spacing={4}>
          {features.map((feature, index) => (
            <Grid2 size={{ xs: 12, sm: 6, md: 3 }} key={index}>
              <Card>
                <CardContent>
                  <Box
                    sx={{ display: "flex", justifyContent: "center", mb: 2 }}
                  >
                    {feature.icon}
                  </Box>
                  <Typography
                    variant="h6"
                    component="h3"
                    gutterBottom
                    align="center"
                  >
                    {feature.title}
                  </Typography>
                  <Typography
                    variant="body2"
                    color="text.secondary"
                    align="center"
                  >
                    {feature.description}
                  </Typography>
                </CardContent>
              </Card>
            </Grid2>
          ))}
        </Grid2>
      </Box> */}
    </main>
  );
}
